version: 2.1
jobs:
  build-linux:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install -y cmake pkg-config ruby ruby-dev
      - run:
          name: Config Git
          command: |
            git config --global init.defaultBranch master
            git config --global user.email "test@gmail.com"
            git config --global user.name "test"
      - run:
          name: Build
          working_directory: ./cli
          command: cargo build
      - run:
          name: Test
          working_directory: ./cli
          command: cargo test
      - run:
          name: Cucumber
          working_directory: ./cucumber
          command: |
            gem install bundler -v 2.3.4
            bundle install
            bundle exec cucumber
      - run:
          name: Build Production
          working_directory: ./cli
          command: cargo build --locked --release --target x86_64-unknown-linux-gnu
      - store_artifacts:
          path: cli/target/x86_64-unknown-linux-gnu/release/vcanrs
          destination: linux-build
      - persist_to_workspace:
          root: .
          paths:
            - cli/target

  publish-github-release:
    machine:
      image: ubuntu-2004:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            GHR_VERSION=0.14.0
            GHR_URL=https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz
            wget "$GHR_URL" && tar xzf ghr_v${GHR_VERSION}_linux_amd64.tar.gz && sudo mv ghr_v${GHR_VERSION}_linux_amd64/ghr /usr/bin/ghr && rm -r ghr_v${GHR_VERSION}_linux_amd64.tar.gz ghr_v${GHR_VERSION}_linux_amd64/
            VERSION=$(cli/target/x86_64-unknown-linux-gnu/release/vcanrs --version | cut -d ' ' -f 2)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./cli/target/x86_64-unknown-linux-gnu/release/vcanrs

workflows:
  ci:
    jobs:
      - build-linux
      - publish-github-release:
          context: public
          requires:
            - build-linux
