version: 2.1
jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install -y cmake pkg-config ruby
      - run:
          name: Config Git
          command: |
            git config --global init.defaultBranch master
            git config --global user.email "test@gmail.com"
            git config --global user.name "test"
      - run:
          name: Build
          working_directory: ./cli
          command: cargo build
      - run:
          name: Test
          working_directory: ./cli
          command: cargo test
      - run:
          name: Cucumber
          working_directory: ./cucumber
          command: |
            gem install bundler -v 2.3.4
            bundle install
            bundle exec cucumber
